// ==ScriptHub==
// @name    AS
// @version 1.0.0
// @adminkey SH-ADMIN-7F3K9-GGS24FG2f-FJFPQNMZ-28FJJ2ZZZDD-444DSDFFJSJFS-2JNCNZXFSF-FJSUSHNBIF-FSFNNASFHFIASHFSUIAJHJDAHS8I374UH5XJXMMXCAAHFUUWUQBQWXVV-FSSDFSHFSF
// ==/ScriptHub==
